<?php

namespace Kevinpurwito\LaravelCountry\Database\Seeders;

use Illuminate\Database\Seeder;
use Kevinpurwito\LaravelCountry\Models\Country;

class CountrySeeder extends Seeder
{
    public function run()
    {
        Country::firstOrCreate(['iso2' => 'AF', 'iso3' => 'AFG', 'code' => '93', 'name' => 'Afghanistan']);
        Country::firstOrCreate(['iso2' => 'AL', 'iso3' => 'ALB', 'code' => '355', 'name' => 'Albania']);
        Country::firstOrCreate(['iso2' => 'DZ', 'iso3' => 'DZA', 'code' => '213', 'name' => 'Algeria']);
        Country::firstOrCreate(['iso2' => 'AS', 'iso3' => 'ASM', 'code' => '1', 'name' => 'American Samoa']);
        Country::firstOrCreate(['iso2' => 'AD', 'iso3' => 'AND', 'code' => '376', 'name' => 'Andorra']);
        Country::firstOrCreate(['iso2' => 'AO', 'iso3' => 'AGO', 'code' => '244', 'name' => 'Angola']);
        Country::firstOrCreate(['iso2' => 'AI', 'iso3' => 'AIA', 'code' => '1', 'name' => 'Anguilla']);
        Country::firstOrCreate(['iso2' => 'AQ', 'iso3' => 'ATA', 'code' => '672', 'name' => 'Antarctica']);
        Country::firstOrCreate(['iso2' => 'AG', 'iso3' => 'ATG', 'code' => '1', 'name' => 'Antigua and Barbuda']);
        Country::firstOrCreate(['iso2' => 'AR', 'iso3' => 'ARG', 'code' => '54', 'name' => 'Argentina']);
        Country::firstOrCreate(['iso2' => 'AM', 'iso3' => 'ARM', 'code' => '374', 'name' => 'Armenia']);
        Country::firstOrCreate(['iso2' => 'AW', 'iso3' => 'ABW', 'code' => '297', 'name' => 'Aruba']);
        Country::firstOrCreate(['iso2' => 'AU', 'iso3' => 'AUS', 'code' => '61', 'name' => 'Australia']);
        Country::firstOrCreate(['iso2' => 'AT', 'iso3' => 'AUT', 'code' => '43', 'name' => 'Austria']);
        Country::firstOrCreate(['iso2' => 'AZ', 'iso3' => 'AZE', 'code' => '994', 'name' => 'Azerbaijan']);
        Country::firstOrCreate(['iso2' => 'BS', 'iso3' => 'BHS', 'code' => '1', 'name' => 'Bahamas']);
        Country::firstOrCreate(['iso2' => 'BH', 'iso3' => 'BHR', 'code' => '973', 'name' => 'Bahrain']);
        Country::firstOrCreate(['iso2' => 'BD', 'iso3' => 'BGD', 'code' => '880', 'name' => 'Bangladesh']);
        Country::firstOrCreate(['iso2' => 'BB', 'iso3' => 'BRB', 'code' => '1', 'name' => 'Barbados']);
        Country::firstOrCreate(['iso2' => 'BY', 'iso3' => 'BLR', 'code' => '375', 'name' => 'Belarus']);
        Country::firstOrCreate(['iso2' => 'BE', 'iso3' => 'BEL', 'code' => '32', 'name' => 'Belgium']);
        Country::firstOrCreate(['iso2' => 'BZ', 'iso3' => 'BLZ', 'code' => '501', 'name' => 'Belize']);
        Country::firstOrCreate(['iso2' => 'BJ', 'iso3' => 'BEN', 'code' => '229', 'name' => 'Benin']);
        Country::firstOrCreate(['iso2' => 'BM', 'iso3' => 'BMU', 'code' => '1', 'name' => 'Bermuda']);
        Country::firstOrCreate(['iso2' => 'BT', 'iso3' => 'BTN', 'code' => '975', 'name' => 'Bhutan']);
        Country::firstOrCreate(['iso2' => 'BO', 'iso3' => 'BOL', 'code' => '591', 'name' => 'Bolivia']);
        Country::firstOrCreate(['iso2' => 'BA', 'iso3' => 'BIH', 'code' => '387', 'name' => 'Bosnia and Herzegovina']);
        Country::firstOrCreate(['iso2' => 'BW', 'iso3' => 'BWA', 'code' => '267', 'name' => 'Botswana']);
        Country::firstOrCreate(['iso2' => 'BR', 'iso3' => 'BRA', 'code' => '55', 'name' => 'Brazil']);
        Country::firstOrCreate(['iso2' => 'IO', 'iso3' => 'IOT', 'code' => '246', 'name' => 'British Indian Ocean Territory']);
        Country::firstOrCreate(['iso2' => 'VG', 'iso3' => 'VGB', 'code' => '1', 'name' => 'British Virgin Islands']);
        Country::firstOrCreate(['iso2' => 'BN', 'iso3' => 'BRN', 'code' => '673', 'name' => 'Brunei']);
        Country::firstOrCreate(['iso2' => 'BG', 'iso3' => 'BGR', 'code' => '359', 'name' => 'Bulgaria']);
        Country::firstOrCreate(['iso2' => 'BF', 'iso3' => 'BFA', 'code' => '226', 'name' => 'Burkina Faso']);
        Country::firstOrCreate(['iso2' => 'BI', 'iso3' => 'BDI', 'code' => '257', 'name' => 'Burundi']);
        Country::firstOrCreate(['iso2' => 'KH', 'iso3' => 'KHM', 'code' => '855', 'name' => 'Cambodia']);
        Country::firstOrCreate(['iso2' => 'CM', 'iso3' => 'CMR', 'code' => '237', 'name' => 'Cameroon']);
        Country::firstOrCreate(['iso2' => 'CA', 'iso3' => 'CAN', 'code' => '1', 'name' => 'Canada']);
        Country::firstOrCreate(['iso2' => 'CV', 'iso3' => 'CPV', 'code' => '238', 'name' => 'Cape Verde']);
        Country::firstOrCreate(['iso2' => 'KY', 'iso3' => 'CYM', 'code' => '1', 'name' => 'Cayman Islands']);
        Country::firstOrCreate(['iso2' => 'CF', 'iso3' => 'CAF', 'code' => '236', 'name' => 'Central African Republic']);
        Country::firstOrCreate(['iso2' => 'TD', 'iso3' => 'TCD', 'code' => '235', 'name' => 'Chad']);
        Country::firstOrCreate(['iso2' => 'CL', 'iso3' => 'CHL', 'code' => '56', 'name' => 'Chile']);
        Country::firstOrCreate(['iso2' => 'CN', 'iso3' => 'CHN', 'code' => '86', 'name' => 'China']);
        Country::firstOrCreate(['iso2' => 'CX', 'iso3' => 'CXR', 'code' => '61', 'name' => 'Christmas Island']);
        Country::firstOrCreate(['iso2' => 'CC', 'iso3' => 'CCK', 'code' => '61', 'name' => 'Cocos Islands']);
        Country::firstOrCreate(['iso2' => 'CO', 'iso3' => 'COL', 'code' => '57', 'name' => 'Colombia']);
        Country::firstOrCreate(['iso2' => 'KM', 'iso3' => 'COM', 'code' => '269', 'name' => 'Comoros']);
        Country::firstOrCreate(['iso2' => 'CK', 'iso3' => 'COK', 'code' => '682', 'name' => 'Cook Islands']);
        Country::firstOrCreate(['iso2' => 'CR', 'iso3' => 'CRI', 'code' => '506', 'name' => 'Costa Rica']);
        Country::firstOrCreate(['iso2' => 'HR', 'iso3' => 'HRV', 'code' => '385', 'name' => 'Croatia']);
        Country::firstOrCreate(['iso2' => 'CU', 'iso3' => 'CUB', 'code' => '53', 'name' => 'Cuba']);
        Country::firstOrCreate(['iso2' => 'CW', 'iso3' => 'CUW', 'code' => '599', 'name' => 'Curacao']);
        Country::firstOrCreate(['iso2' => 'CY', 'iso3' => 'CYP', 'code' => '357', 'name' => 'Cyprus']);
        Country::firstOrCreate(['iso2' => 'CZ', 'iso3' => 'CZE', 'code' => '420', 'name' => 'Czech Republic']);
        Country::firstOrCreate(['iso2' => 'CD', 'iso3' => 'COD', 'code' => '243', 'name' => 'Democratic Republic of the Congo']);
        Country::firstOrCreate(['iso2' => 'DK', 'iso3' => 'DNK', 'code' => '45', 'name' => 'Denmark']);
        Country::firstOrCreate(['iso2' => 'DJ', 'iso3' => 'DJI', 'code' => '253', 'name' => 'Djibouti']);
        Country::firstOrCreate(['iso2' => 'DM', 'iso3' => 'DMA', 'code' => '1', 'name' => 'Dominica']);
        Country::firstOrCreate(['iso2' => 'DO', 'iso3' => 'DOM', 'code' => '1', 'name' => 'Dominican Republic']);
        Country::firstOrCreate(['iso2' => 'TL', 'iso3' => 'TLS', 'code' => '670', 'name' => 'East Timor']);
        Country::firstOrCreate(['iso2' => 'EC', 'iso3' => 'ECU', 'code' => '593', 'name' => 'Ecuador']);
        Country::firstOrCreate(['iso2' => 'EG', 'iso3' => 'EGY', 'code' => '20', 'name' => 'Egypt']);
        Country::firstOrCreate(['iso2' => 'SV', 'iso3' => 'SLV', 'code' => '503', 'name' => 'El Salvador']);
        Country::firstOrCreate(['iso2' => 'GQ', 'iso3' => 'GNQ', 'code' => '240', 'name' => 'Equatorial Guinea']);
        Country::firstOrCreate(['iso2' => 'ER', 'iso3' => 'ERI', 'code' => '291', 'name' => 'Eritrea']);
        Country::firstOrCreate(['iso2' => 'EE', 'iso3' => 'EST', 'code' => '372', 'name' => 'Estonia']);
        Country::firstOrCreate(['iso2' => 'ET', 'iso3' => 'ETH', 'code' => '251', 'name' => 'Ethiopia']);
        Country::firstOrCreate(['iso2' => 'FK', 'iso3' => 'FLK', 'code' => '500', 'name' => 'Falkland Islands']);
        Country::firstOrCreate(['iso2' => 'FO', 'iso3' => 'FRO', 'code' => '298', 'name' => 'Faroe Islands']);
        Country::firstOrCreate(['iso2' => 'FJ', 'iso3' => 'FJI', 'code' => '679', 'name' => 'Fiji']);
        Country::firstOrCreate(['iso2' => 'FI', 'iso3' => 'FIN', 'code' => '358', 'name' => 'Finland']);
        Country::firstOrCreate(['iso2' => 'FR', 'iso3' => 'FRA', 'code' => '33', 'name' => 'France']);
        Country::firstOrCreate(['iso2' => 'PF', 'iso3' => 'PYF', 'code' => '689', 'name' => 'French Polynesia']);
        Country::firstOrCreate(['iso2' => 'GA', 'iso3' => 'GAB', 'code' => '241', 'name' => 'Gabon']);
        Country::firstOrCreate(['iso2' => 'GM', 'iso3' => 'GMB', 'code' => '220', 'name' => 'Gambia']);
        Country::firstOrCreate(['iso2' => 'GE', 'iso3' => 'GEO', 'code' => '995', 'name' => 'Georgia']);
        Country::firstOrCreate(['iso2' => 'DE', 'iso3' => 'DEU', 'code' => '49', 'name' => 'Germany']);
        Country::firstOrCreate(['iso2' => 'GH', 'iso3' => 'GHA', 'code' => '233', 'name' => 'Ghana']);
        Country::firstOrCreate(['iso2' => 'GI', 'iso3' => 'GIB', 'code' => '350', 'name' => 'Gibraltar']);
        Country::firstOrCreate(['iso2' => 'GR', 'iso3' => 'GRC', 'code' => '30', 'name' => 'Greece']);
        Country::firstOrCreate(['iso2' => 'GL', 'iso3' => 'GRL', 'code' => '299', 'name' => 'Greenland']);
        Country::firstOrCreate(['iso2' => 'GD', 'iso3' => 'GRD', 'code' => '1', 'name' => 'Grenada']);
        Country::firstOrCreate(['iso2' => 'GU', 'iso3' => 'GUM', 'code' => '1', 'name' => 'Guam']);
        Country::firstOrCreate(['iso2' => 'GT', 'iso3' => 'GTM', 'code' => '502', 'name' => 'Guatemala']);
        Country::firstOrCreate(['iso2' => 'GG', 'iso3' => 'GGY', 'code' => '44', 'name' => 'Guernsey']);
        Country::firstOrCreate(['iso2' => 'GN', 'iso3' => 'GIN', 'code' => '224', 'name' => 'Guinea']);
        Country::firstOrCreate(['iso2' => 'GW', 'iso3' => 'GNB', 'code' => '245', 'name' => 'Guinea-Bissau']);
        Country::firstOrCreate(['iso2' => 'GY', 'iso3' => 'GUY', 'code' => '592', 'name' => 'Guyana']);
        Country::firstOrCreate(['iso2' => 'HT', 'iso3' => 'HTI', 'code' => '509', 'name' => 'Haiti']);
        Country::firstOrCreate(['iso2' => 'HN', 'iso3' => 'HND', 'code' => '504', 'name' => 'Honduras']);
        Country::firstOrCreate(['iso2' => 'HK', 'iso3' => 'HKG', 'code' => '852', 'name' => 'Hong Kong']);
        Country::firstOrCreate(['iso2' => 'HU', 'iso3' => 'HUN', 'code' => '36', 'name' => 'Hungary']);
        Country::firstOrCreate(['iso2' => 'IS', 'iso3' => 'ISL', 'code' => '354', 'name' => 'Iceland']);
        Country::firstOrCreate(['iso2' => 'IN', 'iso3' => 'IND', 'code' => '91', 'name' => 'India']);
        Country::firstOrCreate(['iso2' => 'ID', 'iso3' => 'IDN', 'code' => '62', 'name' => 'Indonesia']);
        Country::firstOrCreate(['iso2' => 'IR', 'iso3' => 'IRN', 'code' => '98', 'name' => 'Iran']);
        Country::firstOrCreate(['iso2' => 'IQ', 'iso3' => 'IRQ', 'code' => '964', 'name' => 'Iraq']);
        Country::firstOrCreate(['iso2' => 'IE', 'iso3' => 'IRL', 'code' => '353', 'name' => 'Ireland']);
        Country::firstOrCreate(['iso2' => 'IM', 'iso3' => 'IMN', 'code' => '44', 'name' => 'Isle of Man']);
        Country::firstOrCreate(['iso2' => 'IL', 'iso3' => 'ISR', 'code' => '972', 'name' => 'Israel']);
        Country::firstOrCreate(['iso2' => 'IT', 'iso3' => 'ITA', 'code' => '39', 'name' => 'Italy']);
        Country::firstOrCreate(['iso2' => 'CI', 'iso3' => 'CIV', 'code' => '225', 'name' => 'Ivory Coast']);
        Country::firstOrCreate(['iso2' => 'JM', 'iso3' => 'JAM', 'code' => '1', 'name' => 'Jamaica']);
        Country::firstOrCreate(['iso2' => 'JP', 'iso3' => 'JPN', 'code' => '81', 'name' => 'Japan']);
        Country::firstOrCreate(['iso2' => 'JE', 'iso3' => 'JEY', 'code' => '44', 'name' => 'Jersey']);
        Country::firstOrCreate(['iso2' => 'JO', 'iso3' => 'JOR', 'code' => '962', 'name' => 'Jordan']);
        Country::firstOrCreate(['iso2' => 'KZ', 'iso3' => 'KAZ', 'code' => '7', 'name' => 'Kazakhstan']);
        Country::firstOrCreate(['iso2' => 'KE', 'iso3' => 'KEN', 'code' => '254', 'name' => 'Kenya']);
        Country::firstOrCreate(['iso2' => 'KI', 'iso3' => 'KIR', 'code' => '686', 'name' => 'Kiribati']);
        Country::firstOrCreate(['iso2' => 'XK', 'iso3' => 'XKX', 'code' => '383', 'name' => 'Kosovo']);
        Country::firstOrCreate(['iso2' => 'KW', 'iso3' => 'KWT', 'code' => '965', 'name' => 'Kuwait']);
        Country::firstOrCreate(['iso2' => 'KG', 'iso3' => 'KGZ', 'code' => '996', 'name' => 'Kyrgyzstan']);
        Country::firstOrCreate(['iso2' => 'LA', 'iso3' => 'LAO', 'code' => '856', 'name' => 'Laos']);
        Country::firstOrCreate(['iso2' => 'LV', 'iso3' => 'LVA', 'code' => '371', 'name' => 'Latvia']);
        Country::firstOrCreate(['iso2' => 'LB', 'iso3' => 'LBN', 'code' => '961', 'name' => 'Lebanon']);
        Country::firstOrCreate(['iso2' => 'LS', 'iso3' => 'LSO', 'code' => '266', 'name' => 'Lesotho']);
        Country::firstOrCreate(['iso2' => 'LR', 'iso3' => 'LBR', 'code' => '231', 'name' => 'Liberia']);
        Country::firstOrCreate(['iso2' => 'LY', 'iso3' => 'LBY', 'code' => '218', 'name' => 'Libya']);
        Country::firstOrCreate(['iso2' => 'LI', 'iso3' => 'LIE', 'code' => '423', 'name' => 'Liechtenstein']);
        Country::firstOrCreate(['iso2' => 'LT', 'iso3' => 'LTU', 'code' => '370', 'name' => 'Lithuania']);
        Country::firstOrCreate(['iso2' => 'LU', 'iso3' => 'LUX', 'code' => '352', 'name' => 'Luxembourg']);
        Country::firstOrCreate(['iso2' => 'MO', 'iso3' => 'MAC', 'code' => '853', 'name' => 'Macau']);
        Country::firstOrCreate(['iso2' => 'MK', 'iso3' => 'MKD', 'code' => '389', 'name' => 'Macedonia']);
        Country::firstOrCreate(['iso2' => 'MG', 'iso3' => 'MDG', 'code' => '261', 'name' => 'Madagascar']);
        Country::firstOrCreate(['iso2' => 'MW', 'iso3' => 'MWI', 'code' => '265', 'name' => 'Malawi']);
        Country::firstOrCreate(['iso2' => 'MY', 'iso3' => 'MYS', 'code' => '60', 'name' => 'Malaysia']);
        Country::firstOrCreate(['iso2' => 'MV', 'iso3' => 'MDV', 'code' => '960', 'name' => 'Maldives']);
        Country::firstOrCreate(['iso2' => 'ML', 'iso3' => 'MLI', 'code' => '223', 'name' => 'Mali']);
        Country::firstOrCreate(['iso2' => 'MT', 'iso3' => 'MLT', 'code' => '356', 'name' => 'Malta']);
        Country::firstOrCreate(['iso2' => 'MH', 'iso3' => 'MHL', 'code' => '692', 'name' => 'Marshall Islands']);
        Country::firstOrCreate(['iso2' => 'MR', 'iso3' => 'MRT', 'code' => '222', 'name' => 'Mauritania']);
        Country::firstOrCreate(['iso2' => 'MU', 'iso3' => 'MUS', 'code' => '230', 'name' => 'Mauritius']);
        Country::firstOrCreate(['iso2' => 'YT', 'iso3' => 'MYT', 'code' => '262', 'name' => 'Mayotte']);
        Country::firstOrCreate(['iso2' => 'MX', 'iso3' => 'MEX', 'code' => '52', 'name' => 'Mexico']);
        Country::firstOrCreate(['iso2' => 'FM', 'iso3' => 'FSM', 'code' => '691', 'name' => 'Micronesia']);
        Country::firstOrCreate(['iso2' => 'MD', 'iso3' => 'MDA', 'code' => '373', 'name' => 'Moldova']);
        Country::firstOrCreate(['iso2' => 'MC', 'iso3' => 'MCO', 'code' => '377', 'name' => 'Monaco']);
        Country::firstOrCreate(['iso2' => 'MN', 'iso3' => 'MNG', 'code' => '976', 'name' => 'Mongolia']);
        Country::firstOrCreate(['iso2' => 'ME', 'iso3' => 'MNE', 'code' => '382', 'name' => 'Montenegro']);
        Country::firstOrCreate(['iso2' => 'MS', 'iso3' => 'MSR', 'code' => '1', 'name' => 'Montserrat']);
        Country::firstOrCreate(['iso2' => 'MA', 'iso3' => 'MAR', 'code' => '212', 'name' => 'Morocco']);
        Country::firstOrCreate(['iso2' => 'MZ', 'iso3' => 'MOZ', 'code' => '258', 'name' => 'Mozambique']);
        Country::firstOrCreate(['iso2' => 'MM', 'iso3' => 'MMR', 'code' => '95', 'name' => 'Myanmar']);
        Country::firstOrCreate(['iso2' => 'NA', 'iso3' => 'NAM', 'code' => '264', 'name' => 'Namibia']);
        Country::firstOrCreate(['iso2' => 'NR', 'iso3' => 'NRU', 'code' => '674', 'name' => 'Nauru']);
        Country::firstOrCreate(['iso2' => 'NP', 'iso3' => 'NPL', 'code' => '977', 'name' => 'Nepal']);
        Country::firstOrCreate(['iso2' => 'NL', 'iso3' => 'NLD', 'code' => '31', 'name' => 'Netherlands']);
        Country::firstOrCreate(['iso2' => 'AN', 'iso3' => 'ANT', 'code' => '599', 'name' => 'Netherlands Antilles']);
        Country::firstOrCreate(['iso2' => 'NC', 'iso3' => 'NCL', 'code' => '687', 'name' => 'New Caledonia']);
        Country::firstOrCreate(['iso2' => 'NZ', 'iso3' => 'NZL', 'code' => '64', 'name' => 'New Zealand']);
        Country::firstOrCreate(['iso2' => 'NI', 'iso3' => 'NIC', 'code' => '505', 'name' => 'Nicaragua']);
        Country::firstOrCreate(['iso2' => 'NE', 'iso3' => 'NER', 'code' => '227', 'name' => 'Niger']);
        Country::firstOrCreate(['iso2' => 'NG', 'iso3' => 'NGA', 'code' => '234', 'name' => 'Nigeria']);
        Country::firstOrCreate(['iso2' => 'NU', 'iso3' => 'NIU', 'code' => '683', 'name' => 'Niue']);
        Country::firstOrCreate(['iso2' => 'KP', 'iso3' => 'PRK', 'code' => '850', 'name' => 'North Korea']);
        Country::firstOrCreate(['iso2' => 'MP', 'iso3' => 'MNP', 'code' => '1', 'name' => 'Northern Mariana Islands']);
        Country::firstOrCreate(['iso2' => 'NO', 'iso3' => 'NOR', 'code' => '47', 'name' => 'Norway']);
        Country::firstOrCreate(['iso2' => 'OM', 'iso3' => 'OMN', 'code' => '968', 'name' => 'Oman']);
        Country::firstOrCreate(['iso2' => 'PK', 'iso3' => 'PAK', 'code' => '92', 'name' => 'Pakistan']);
        Country::firstOrCreate(['iso2' => 'PW', 'iso3' => 'PLW', 'code' => '680', 'name' => 'Palau']);
        Country::firstOrCreate(['iso2' => 'PS', 'iso3' => 'PSE', 'code' => '970', 'name' => 'Palestine']);
        Country::firstOrCreate(['iso2' => 'PA', 'iso3' => 'PAN', 'code' => '507', 'name' => 'Panama']);
        Country::firstOrCreate(['iso2' => 'PG', 'iso3' => 'PNG', 'code' => '675', 'name' => 'Papua New Guinea']);
        Country::firstOrCreate(['iso2' => 'PY', 'iso3' => 'PRY', 'code' => '595', 'name' => 'Paraguay']);
        Country::firstOrCreate(['iso2' => 'PE', 'iso3' => 'PER', 'code' => '51', 'name' => 'Peru']);
        Country::firstOrCreate(['iso2' => 'PH', 'iso3' => 'PHL', 'code' => '63', 'name' => 'Philippines']);
        Country::firstOrCreate(['iso2' => 'PN', 'iso3' => 'PCN', 'code' => '64', 'name' => 'Pitcairn']);
        Country::firstOrCreate(['iso2' => 'PL', 'iso3' => 'POL', 'code' => '48', 'name' => 'Poland']);
        Country::firstOrCreate(['iso2' => 'PT', 'iso3' => 'PRT', 'code' => '351', 'name' => 'Portugal']);
        Country::firstOrCreate(['iso2' => 'PR', 'iso3' => 'PRI', 'code' => '1', 'name' => 'Puerto Rico']);
        Country::firstOrCreate(['iso2' => 'QA', 'iso3' => 'QAT', 'code' => '974', 'name' => 'Qatar']);
        Country::firstOrCreate(['iso2' => 'CG', 'iso3' => 'COG', 'code' => '242', 'name' => 'Republic of the Congo']);
        Country::firstOrCreate(['iso2' => 'RE', 'iso3' => 'REU', 'code' => '262', 'name' => 'Reunion']);
        Country::firstOrCreate(['iso2' => 'RO', 'iso3' => 'ROU', 'code' => '40', 'name' => 'Romania']);
        Country::firstOrCreate(['iso2' => 'RU', 'iso3' => 'RUS', 'code' => '7', 'name' => 'Russia']);
        Country::firstOrCreate(['iso2' => 'RW', 'iso3' => 'RWA', 'code' => '250', 'name' => 'Rwanda']);
        Country::firstOrCreate(['iso2' => 'BL', 'iso3' => 'BLM', 'code' => '590', 'name' => 'Saint Barthelemy']);
        Country::firstOrCreate(['iso2' => 'SH', 'iso3' => 'SHN', 'code' => '290', 'name' => 'Saint Helena']);
        Country::firstOrCreate(['iso2' => 'KN', 'iso3' => 'KNA', 'code' => '1', 'name' => 'Saint Kitts and Nevis']);
        Country::firstOrCreate(['iso2' => 'LC', 'iso3' => 'LCA', 'code' => '1', 'name' => 'Saint Lucia']);
        Country::firstOrCreate(['iso2' => 'MF', 'iso3' => 'MAF', 'code' => '590', 'name' => 'Saint Martin']);
        Country::firstOrCreate(['iso2' => 'PM', 'iso3' => 'SPM', 'code' => '508', 'name' => 'Saint Pierre and Miquelon']);
        Country::firstOrCreate(['iso2' => 'VC', 'iso3' => 'VCT', 'code' => '1', 'name' => 'Saint Vincent and the Grenadines']);
        Country::firstOrCreate(['iso2' => 'WS', 'iso3' => 'WSM', 'code' => '685', 'name' => 'Samoa']);
        Country::firstOrCreate(['iso2' => 'SM', 'iso3' => 'SMR', 'code' => '378', 'name' => 'San Marino']);
        Country::firstOrCreate(['iso2' => 'ST', 'iso3' => 'STP', 'code' => '239', 'name' => 'Sao Tome and Principe']);
        Country::firstOrCreate(['iso2' => 'SA', 'iso3' => 'SAU', 'code' => '966', 'name' => 'Saudi Arabia']);
        Country::firstOrCreate(['iso2' => 'SN', 'iso3' => 'SEN', 'code' => '221', 'name' => 'Senegal']);
        Country::firstOrCreate(['iso2' => 'RS', 'iso3' => 'SRB', 'code' => '381', 'name' => 'Serbia']);
        Country::firstOrCreate(['iso2' => 'SC', 'iso3' => 'SYC', 'code' => '248', 'name' => 'Seychelles']);
        Country::firstOrCreate(['iso2' => 'SL', 'iso3' => 'SLE', 'code' => '232', 'name' => 'Sierra Leone']);
        Country::firstOrCreate(['iso2' => 'SG', 'iso3' => 'SGP', 'code' => '65', 'name' => 'Singapore']);
        Country::firstOrCreate(['iso2' => 'SX', 'iso3' => 'SXM', 'code' => '1', 'name' => 'Sint Maarten']);
        Country::firstOrCreate(['iso2' => 'SK', 'iso3' => 'SVK', 'code' => '421', 'name' => 'Slovakia']);
        Country::firstOrCreate(['iso2' => 'SI', 'iso3' => 'SVN', 'code' => '386', 'name' => 'Slovenia']);
        Country::firstOrCreate(['iso2' => 'SB', 'iso3' => 'SLB', 'code' => '677', 'name' => 'Solomon Islands']);
        Country::firstOrCreate(['iso2' => 'SO', 'iso3' => 'SOM', 'code' => '252', 'name' => 'Somalia']);
        Country::firstOrCreate(['iso2' => 'ZA', 'iso3' => 'ZAF', 'code' => '27', 'name' => 'South Africa']);
        Country::firstOrCreate(['iso2' => 'KR', 'iso3' => 'KOR', 'code' => '82', 'name' => 'South Korea']);
        Country::firstOrCreate(['iso2' => 'SS', 'iso3' => 'SSD', 'code' => '211', 'name' => 'South Sudan']);
        Country::firstOrCreate(['iso2' => 'ES', 'iso3' => 'ESP', 'code' => '34', 'name' => 'Spain']);
        Country::firstOrCreate(['iso2' => 'LK', 'iso3' => 'LKA', 'code' => '94', 'name' => 'Sri Lanka']);
        Country::firstOrCreate(['iso2' => 'SD', 'iso3' => 'SDN', 'code' => '249', 'name' => 'Sudan']);
        Country::firstOrCreate(['iso2' => 'SR', 'iso3' => 'SUR', 'code' => '597', 'name' => 'Suriname']);
        Country::firstOrCreate(['iso2' => 'SJ', 'iso3' => 'SJM', 'code' => '47', 'name' => 'Svalbard and Jan Mayen']);
        Country::firstOrCreate(['iso2' => 'SZ', 'iso3' => 'SWZ', 'code' => '268', 'name' => 'Swaziland']);
        Country::firstOrCreate(['iso2' => 'SE', 'iso3' => 'SWE', 'code' => '46', 'name' => 'Sweden']);
        Country::firstOrCreate(['iso2' => 'CH', 'iso3' => 'CHE', 'code' => '41', 'name' => 'Switzerland']);
        Country::firstOrCreate(['iso2' => 'SY', 'iso3' => 'SYR', 'code' => '963', 'name' => 'Syria']);
        Country::firstOrCreate(['iso2' => 'TW', 'iso3' => 'TWN', 'code' => '886', 'name' => 'Taiwan']);
        Country::firstOrCreate(['iso2' => 'TJ', 'iso3' => 'TJK', 'code' => '992', 'name' => 'Tajikistan']);
        Country::firstOrCreate(['iso2' => 'TZ', 'iso3' => 'TZA', 'code' => '255', 'name' => 'Tanzania']);
        Country::firstOrCreate(['iso2' => 'TH', 'iso3' => 'THA', 'code' => '66', 'name' => 'Thailand']);
        Country::firstOrCreate(['iso2' => 'TG', 'iso3' => 'TGO', 'code' => '228', 'name' => 'Togo']);
        Country::firstOrCreate(['iso2' => 'TK', 'iso3' => 'TKL', 'code' => '690', 'name' => 'Tokelau']);
        Country::firstOrCreate(['iso2' => 'TO', 'iso3' => 'TON', 'code' => '676', 'name' => 'Tonga']);
        Country::firstOrCreate(['iso2' => 'TT', 'iso3' => 'TTO', 'code' => '1', 'name' => 'Trinidad and Tobago']);
        Country::firstOrCreate(['iso2' => 'TN', 'iso3' => 'TUN', 'code' => '216', 'name' => 'Tunisia']);
        Country::firstOrCreate(['iso2' => 'TR', 'iso3' => 'TUR', 'code' => '90', 'name' => 'Turkey']);
        Country::firstOrCreate(['iso2' => 'TM', 'iso3' => 'TKM', 'code' => '993', 'name' => 'Turkmenistan']);
        Country::firstOrCreate(['iso2' => 'TC', 'iso3' => 'TCA', 'code' => '1', 'name' => 'Turks and Caicos Islands']);
        Country::firstOrCreate(['iso2' => 'TV', 'iso3' => 'TUV', 'code' => '688', 'name' => 'Tuvalu']);
        Country::firstOrCreate(['iso2' => 'VI', 'iso3' => 'VIR', 'code' => '1', 'name' => 'U.S. Virgin Islands']);
        Country::firstOrCreate(['iso2' => 'UG', 'iso3' => 'UGA', 'code' => '256', 'name' => 'Uganda']);
        Country::firstOrCreate(['iso2' => 'UA', 'iso3' => 'UKR', 'code' => '380', 'name' => 'Ukraine']);
        Country::firstOrCreate(['iso2' => 'AE', 'iso3' => 'ARE', 'code' => '971', 'name' => 'United Arab Emirates']);
        Country::firstOrCreate(['iso2' => 'GB', 'iso3' => 'GBR', 'code' => '44', 'name' => 'United Kingdom']);
        Country::firstOrCreate(['iso2' => 'US', 'iso3' => 'USA', 'code' => '1', 'name' => 'United States']);
        Country::firstOrCreate(['iso2' => 'UY', 'iso3' => 'URY', 'code' => '598', 'name' => 'Uruguay']);
        Country::firstOrCreate(['iso2' => 'UZ', 'iso3' => 'UZB', 'code' => '998', 'name' => 'Uzbekistan']);
        Country::firstOrCreate(['iso2' => 'VU', 'iso3' => 'VUT', 'code' => '678', 'name' => 'Vanuatu']);
        Country::firstOrCreate(['iso2' => 'VA', 'iso3' => 'VAT', 'code' => '379', 'name' => 'Vatican']);
        Country::firstOrCreate(['iso2' => 'VE', 'iso3' => 'VEN', 'code' => '58', 'name' => 'Venezuela']);
        Country::firstOrCreate(['iso2' => 'VN', 'iso3' => 'VNM', 'code' => '84', 'name' => 'Vietnam']);
        Country::firstOrCreate(['iso2' => 'WF', 'iso3' => 'WLF', 'code' => '681', 'name' => 'Wallis and Futuna']);
        Country::firstOrCreate(['iso2' => 'EH', 'iso3' => 'ESH', 'code' => '212', 'name' => 'Western Sahara']);
        Country::firstOrCreate(['iso2' => 'YE', 'iso3' => 'YEM', 'code' => '967', 'name' => 'Yemen']);
        Country::firstOrCreate(['iso2' => 'ZM', 'iso3' => 'ZMB', 'code' => '260', 'name' => 'Zambia']);
        Country::firstOrCreate(['iso2' => 'ZW', 'iso3' => 'ZWE', 'code' => '263', 'name' => 'Zimbabwe']);
    }
}
