<?php

namespace Kevinpurwito\LaravelCountry\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Kevinpurwito\LaravelCountry\Models\Country;

class IdCitiesSeeder extends Seeder
{
    public function run()
    {
        $provinceTable = config('kp_country.table_names.province', 'provinces');
        if (! Schema::hasTable($provinceTable)) {
            return false;
        }

        $cityTable = config('kp_country.table_names.city', 'cities');
        if (! Schema::hasTable($cityTable)) {
            return false;
        }

        $country = Country::with(['provinces'])->whereIso3('IDN')->first(); // Indonesia

        ($country->provinces->firstWhere('code', '11'))->createCity('11.05', 'Kab. Aceh Barat');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.12', 'Kab. Aceh Barat Daya');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.06', 'Kab. Aceh Besar');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.14', 'Kab. Aceh Jaya');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.01', 'Kab. Aceh Selatan');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.10', 'Kab. Aceh Singkil');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.16', 'Kab. Aceh Tamiang');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.04', 'Kab. Aceh Tengah');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.02', 'Kab. Aceh Tenggara');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.03', 'Kab. Aceh Timur');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.08', 'Kab. Aceh Utara');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.17', 'Kab. Bener Meriah');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.11', 'Kab. Bireuen');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.13', 'Kab. Gayo Lues');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.15', 'Kab. Nagan Raya');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.07', 'Kab. Pidie');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.18', 'Kab. Pidie Jaya');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.09', 'Kab. Simeulue');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.71', 'Kota Banda Aceh');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.74', 'Kota Langsa');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.73', 'Kota Lhokseumawe');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.72', 'Kota Sabang');
        ($country->provinces->firstWhere('code', '11'))->createCity('11.75', 'Kota Subulussalam');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.09', 'Kab. Asahan');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.19', 'Kab. Batu Bara');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.11', 'Kab. Dairi');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.07', 'Kab. Deli Serdang');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.16', 'Kab. Humbang Hasundutan');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.06', 'Kab. Karo');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.10', 'Kab. Labuhanbatu');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.22', 'Kab. Labuhanbatu Selatan');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.23', 'Kab. Labuhanbatu Utara');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.05', 'Kab. Langkat');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.13', 'Kab. Mandailing Natal');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.04', 'Kab. Nias');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.25', 'Kab. Nias Barat');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.14', 'Kab. Nias Selatan');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.24', 'Kab. Nias Utara');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.21', 'Kab. Padang Lawas');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.20', 'Kab. Padang Lawas Utara');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.15', 'Kab. Pakpak Bharat');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.17', 'Kab. Samosir');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.18', 'Kab. Serdang Bedagai');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.08', 'Kab. Simalungun');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.03', 'Kab. Tapanuli Selatan');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.01', 'Kab. Tapanuli Tengah');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.02', 'Kab. Tapanuli Utara');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.12', 'Kab. Toba');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.75', 'Kota Binjai');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.78', 'Kota Gunungsitoli');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.71', 'Kota Medan');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.77', 'Kota Padang Sidempuan');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.72', 'Kota Pematang Siantar');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.73', 'Kota Sibolga');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.74', 'Kota Tanjung Balai');
        ($country->provinces->firstWhere('code', '12'))->createCity('12.76', 'Kota Tebing Tinggi');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.06', 'Kab. Agam');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.10', 'Kab. Dharmasraya');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.09', 'Kab. Kepulauan Mentawai');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.07', 'Kab. Lima Puluh Koto');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.05', 'Kab. Padang Pariaman');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.08', 'Kab. Pasaman');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.12', 'Kab. Pasaman Barat');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.01', 'Kab. Pesisir Selatan');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.03', 'Kab. Sijunjung');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.02', 'Kab. Solok');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.11', 'Kab. Solok Selatan');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.04', 'Kab. Tanah Datar');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.75', 'Kota Bukittinggi');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.71', 'Kota Padang');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.74', 'Kota Padang Panjang');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.77', 'Kota Pariaman');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.76', 'Kota Payakumbuh');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.73', 'Kota Sawahlunto');
        ($country->provinces->firstWhere('code', '13'))->createCity('13.72', 'Kota Solok');
        ($country->provinces->firstWhere('code', '17'))->createCity('17.01', 'Kab. Bengkulu Selatan');
        ($country->provinces->firstWhere('code', '17'))->createCity('17.09', 'Kab. Bengkulu Tengah');
        ($country->provinces->firstWhere('code', '17'))->createCity('17.03', 'Kab. Bengkulu Utara');
        ($country->provinces->firstWhere('code', '17'))->createCity('17.04', 'Kab. Kaur');
        ($country->provinces->firstWhere('code', '17'))->createCity('17.08', 'Kab. Kepahiang');
        ($country->provinces->firstWhere('code', '17'))->createCity('17.07', 'Kab. Lebong');
        ($country->provinces->firstWhere('code', '17'))->createCity('17.06', 'Kab. Muko-muko');
        ($country->provinces->firstWhere('code', '17'))->createCity('17.02', 'Kab. Rejang Lebong');
        ($country->provinces->firstWhere('code', '17'))->createCity('17.05', 'Kab. Seluma');
        ($country->provinces->firstWhere('code', '17'))->createCity('17.71', 'Kota Bengkulu');
        ($country->provinces->firstWhere('code', '14'))->createCity('14.03', 'Kab. Bengkalis');
        ($country->provinces->firstWhere('code', '14'))->createCity('14.04', 'Kab. Indragiri Hilir');
        ($country->provinces->firstWhere('code', '14'))->createCity('14.02', 'Kab. Indragiri Hulu');
        ($country->provinces->firstWhere('code', '14'))->createCity('14.01', 'Kab. Kampar');
        ($country->provinces->firstWhere('code', '14'))->createCity('14.10', 'Kab. Kepulauan Meranti');
        ($country->provinces->firstWhere('code', '14'))->createCity('14.09', 'Kab. Kuantan Singingi');
        ($country->provinces->firstWhere('code', '14'))->createCity('14.05', 'Kab. Pelalawan');
        ($country->provinces->firstWhere('code', '14'))->createCity('14.07', 'Kab. Rokan Hilir');
        ($country->provinces->firstWhere('code', '14'))->createCity('14.06', 'Kab. Rokan Hulu');
        ($country->provinces->firstWhere('code', '14'))->createCity('14.08', 'Kab. Siak');
        ($country->provinces->firstWhere('code', '14'))->createCity('14.72', 'Kota Dumai');
        ($country->provinces->firstWhere('code', '14'))->createCity('14.71', 'Kota Pekanbaru');
        ($country->provinces->firstWhere('code', '21'))->createCity('21.01', 'Kab. Bintan');
        ($country->provinces->firstWhere('code', '21'))->createCity('21.02', 'Kab. Karimun');
        ($country->provinces->firstWhere('code', '21'))->createCity('21.05', 'Kab. Kepulauan Anambas');
        ($country->provinces->firstWhere('code', '21'))->createCity('21.04', 'Kab. Lingga');
        ($country->provinces->firstWhere('code', '21'))->createCity('21.03', 'Kab. Natuna');
        ($country->provinces->firstWhere('code', '21'))->createCity('21.71', 'Kota Batam');
        ($country->provinces->firstWhere('code', '21'))->createCity('21.72', 'Kota Tanjung Pinang');
        ($country->provinces->firstWhere('code', '15'))->createCity('15.04', 'Kab. Batang Hari');
        ($country->provinces->firstWhere('code', '15'))->createCity('15.08', 'Kab. Bungo');
        ($country->provinces->firstWhere('code', '15'))->createCity('15.01', 'Kab. Kerinci');
        ($country->provinces->firstWhere('code', '15'))->createCity('15.02', 'Kab. Merangin');
        ($country->provinces->firstWhere('code', '15'))->createCity('15.05', 'Kab. Muaro Jambi');
        ($country->provinces->firstWhere('code', '15'))->createCity('15.03', 'Kab. Sarolangun');
        ($country->provinces->firstWhere('code', '15'))->createCity('15.06', 'Kab. Tanjung Jabung Barat');
        ($country->provinces->firstWhere('code', '15'))->createCity('15.07', 'Kab. Tanjung Jabung Timur');
        ($country->provinces->firstWhere('code', '15'))->createCity('15.09', 'Kab. Tebo');
        ($country->provinces->firstWhere('code', '15'))->createCity('15.71', 'Kota Jambi');
        ($country->provinces->firstWhere('code', '15'))->createCity('15.72', 'Kota Sungai Penuh');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.07', 'Kab. Banyuasin');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.11', 'Kab. Empat Lawang');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.04', 'Kab. Lahat');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.03', 'Kab. Muara Enim');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.06', 'Kab. Musi Banyuasin');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.05', 'Kab. Musi Rawas');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.13', 'Kab. Musi Rawas Utara');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.10', 'Kab. Ogan Ilir');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.02', 'Kab. Ogan Komering Ilir');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.01', 'Kab. Ogan Komering Ulu');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.09', 'Kab. Ogan Komering Ulu Selatan');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.08', 'Kab. Ogan Komering Ulu Timur');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.12', 'Kab. Penukal Abab Lematang Ilir');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.73', 'Kota Lubuk Linggau');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.72', 'Kota Pagar Alam');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.71', 'Kota Palembang');
        ($country->provinces->firstWhere('code', '16'))->createCity('16.74', 'Kota Prabumulih');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.04', 'Kab. Lampung Barat');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.01', 'Kab. Lampung Selatan');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.02', 'Kab. Lampung Tengah');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.07', 'Kab. Lampung Timur');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.03', 'Kab. Lampung Utara');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.11', 'Kab. Mesuji');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.09', 'Kab. Pesawaran');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.13', 'Kab. Pesisir Barat');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.10', 'Kab. Pringsewu');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.06', 'Kab. Tanggamus');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.05', 'Kab. Tulang Bawang');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.12', 'Kab. Tulang Bawang Barat');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.08', 'Kab. Way Kanan');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.71', 'Kota Bandar Lampung');
        ($country->provinces->firstWhere('code', '18'))->createCity('18.72', 'Kota Metro');
        ($country->provinces->firstWhere('code', '19'))->createCity('19.01', 'Kab. Bangka');
        ($country->provinces->firstWhere('code', '19'))->createCity('19.05', 'Kab. Bangka Barat');
        ($country->provinces->firstWhere('code', '19'))->createCity('19.03', 'Kab. Bangka Selatan');
        ($country->provinces->firstWhere('code', '19'))->createCity('19.04', 'Kab. Bangka Tengah');
        ($country->provinces->firstWhere('code', '19'))->createCity('19.02', 'Kab. Belitung');
        ($country->provinces->firstWhere('code', '19'))->createCity('19.06', 'Kab. Belitung Timur');
        ($country->provinces->firstWhere('code', '19'))->createCity('19.71', 'Kota Pangkal Pinang');
        ($country->provinces->firstWhere('code', '31'))->createCity('31.01', 'Kab. Kepulauan Seribu');
        ($country->provinces->firstWhere('code', '31'))->createCity('31.73', 'Kota Jakarta Barat');
        ($country->provinces->firstWhere('code', '31'))->createCity('31.71', 'Kota Jakarta Pusat');
        ($country->provinces->firstWhere('code', '31'))->createCity('31.74', 'Kota Jakarta Selatan');
        ($country->provinces->firstWhere('code', '31'))->createCity('31.75', 'Kota Jakarta Timur');
        ($country->provinces->firstWhere('code', '31'))->createCity('31.72', 'Kota Jakarta Utara');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.04', 'Kab. Bandung');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.17', 'Kab. Bandung Barat');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.16', 'Kab. Bekasi');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.01', 'Kab. Bogor');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.07', 'Kab. Ciamis');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.03', 'Kab. Cianjur');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.09', 'Kab. Cirebon');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.05', 'Kab. Garut');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.12', 'Kab. Indramayu');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.15', 'Kab. Karawang');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.08', 'Kab. Kuningan');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.10', 'Kab. Majalengka');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.18', 'Kab. Pangandaran');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.14', 'Kab. Purwakarta');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.13', 'Kab. Subang');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.02', 'Kab. Sukabumi');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.11', 'Kab. Sumedang');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.06', 'Kab. Tasikmalaya');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.73', 'Kota Bandung');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.79', 'Kota Banjar');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.75', 'Kota Bekasi');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.71', 'Kota Bogor');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.77', 'Kota Cimahi');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.74', 'Kota Cirebon');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.76', 'Kota Depok');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.72', 'Kota Sukabumi');
        ($country->provinces->firstWhere('code', '32'))->createCity('32.78', 'Kota Tasikmalaya');
        ($country->provinces->firstWhere('code', '36'))->createCity('36.02', 'Kab. Lebak');
        ($country->provinces->firstWhere('code', '36'))->createCity('36.01', 'Kab. Pandeglang');
        ($country->provinces->firstWhere('code', '36'))->createCity('36.04', 'Kab. Serang');
        ($country->provinces->firstWhere('code', '36'))->createCity('36.03', 'Kab. Tangerang');
        ($country->provinces->firstWhere('code', '36'))->createCity('36.71', 'Kota Tangerang');
        ($country->provinces->firstWhere('code', '36'))->createCity('36.72', 'Kota Cilegon');
        ($country->provinces->firstWhere('code', '36'))->createCity('36.73', 'Kota Serang');
        ($country->provinces->firstWhere('code', '36'))->createCity('36.74', 'Kota Tangerang Selatan');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.04', 'Kab. Banjarnegara');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.02', 'Kab. Banyumas');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.25', 'Kab. Batang');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.16', 'Kab. Blora');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.09', 'Kab. Boyolali');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.29', 'Kab. Brebes');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.01', 'Kab. Cilacap');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.21', 'Kab. Demak');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.15', 'Kab. Grobogan');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.20', 'Kab. Jepara');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.13', 'Kab. Karanganyar');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.05', 'Kab. Kebumen');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.24', 'Kab. Kendal');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.10', 'Kab. Klaten');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.19', 'Kab. Kudus');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.08', 'Kab. Magelang');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.18', 'Kab. Pati');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.26', 'Kab. Pekalongan');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.27', 'Kab. Pemalang');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.03', 'Kab. Purbalingga');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.06', 'Kab. Purworejo');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.17', 'Kab. Rembang');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.14', 'Kab. Sragen');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.22', 'Kab. Semarang');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.11', 'Kab. Sukoharjo');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.23', 'Kab. Temanggung');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.28', 'Kab. Tegal');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.12', 'Kab. Wonogiri');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.07', 'Kab. Wonosobo');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.71', 'Kota Magelang');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.75', 'Kota Pekalongan');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.72', 'Kota Surakarta');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.73', 'Kota Salatiga');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.74', 'Kota Semarang');
        ($country->provinces->firstWhere('code', '33'))->createCity('33.76', 'Kota Tegal');
        ($country->provinces->firstWhere('code', '34'))->createCity('34.02', 'Kab. Bantul');
        ($country->provinces->firstWhere('code', '34'))->createCity('34.03', 'Kab. Gunung Kidul');
        ($country->provinces->firstWhere('code', '34'))->createCity('34.01', 'Kab. Kulon Progo');
        ($country->provinces->firstWhere('code', '34'))->createCity('34.04', 'Kab. Sleman');
        ($country->provinces->firstWhere('code', '34'))->createCity('34.71', 'Kota Yogyakarta');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.26', 'Kab. Bangkalan');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.10', 'Kab. Banyuwangi');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.05', 'Kab. Blitar');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.22', 'Kab. Bojonegoro');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.11', 'Kab. Bondowoso');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.25', 'Kab. Gresik');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.09', 'Kab. Jember');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.17', 'Kab. Jombang');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.06', 'Kab. Kediri');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.24', 'Kab. Lamongan');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.08', 'Kab. Lumajang');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.19', 'Kab. Madiun');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.20', 'Kab. Magetan');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.07', 'Kab. Malang');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.16', 'Kab. Mojokerto');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.18', 'Kab. Nganjuk');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.21', 'Kab. Ngawi');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.01', 'Kab. Pacitan');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.28', 'Kab. Pamekasan');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.14', 'Kab. Pasuruan');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.02', 'Kab. Ponorogo');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.13', 'Kab. Probolinggo');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.27', 'Kab. Sampang');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.15', 'Kab. Sidoarjo');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.12', 'Kab. Situbondo');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.29', 'Kab. Sumenep');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.03', 'Kab. Trenggalek');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.23', 'Kab. Tuban');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.04', 'Kab. Tulungagung');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.79', 'Kota Batu');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.72', 'Kota Blitar');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.71', 'Kota Kediri');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.77', 'Kota Madiun');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.73', 'Kota Malang');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.76', 'Kota Mojokerto');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.75', 'Kota Pasuruan');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.74', 'Kota Probolinggo');
        ($country->provinces->firstWhere('code', '35'))->createCity('35.78', 'Kota Surabaya');
        ($country->provinces->firstWhere('code', '61'))->createCity('61.07', 'Kab. Bengkayang');
        ($country->provinces->firstWhere('code', '61'))->createCity('61.06', 'Kab. Kapuas Hulu');
        ($country->provinces->firstWhere('code', '61'))->createCity('61.11', 'Kab. Kayong Utara');
        ($country->provinces->firstWhere('code', '61'))->createCity('61.04', 'Kab. Ketapang');
        ($country->provinces->firstWhere('code', '61'))->createCity('61.12', 'Kab. Kubu Raya');
        ($country->provinces->firstWhere('code', '61'))->createCity('61.08', 'Kab. Landak');
        ($country->provinces->firstWhere('code', '61'))->createCity('61.10', 'Kab. Melawi');
        ($country->provinces->firstWhere('code', '61'))->createCity('61.02', 'Kab. Mempawah');
        ($country->provinces->firstWhere('code', '61'))->createCity('61.01', 'Kab. Sambas');
        ($country->provinces->firstWhere('code', '61'))->createCity('61.03', 'Kab. Sanggau');
        ($country->provinces->firstWhere('code', '61'))->createCity('61.09', 'Kab. Sekadau');
        ($country->provinces->firstWhere('code', '61'))->createCity('61.05', 'Kab. Sintang');
        ($country->provinces->firstWhere('code', '61'))->createCity('61.71', 'Kota Pontianak');
        ($country->provinces->firstWhere('code', '61'))->createCity('61.72', 'Kota Singkawang');
        ($country->provinces->firstWhere('code', '63'))->createCity('63.11', 'Kab. Balangan');
        ($country->provinces->firstWhere('code', '63'))->createCity('63.03', 'Kab. Banjar');
        ($country->provinces->firstWhere('code', '63'))->createCity('63.04', 'Kab. Barito Kuala');
        ($country->provinces->firstWhere('code', '63'))->createCity('63.06', 'Kab. Hulu Sungai Selatan');
        ($country->provinces->firstWhere('code', '63'))->createCity('63.07', 'Kab. Hulu Sungai Tengah');
        ($country->provinces->firstWhere('code', '63'))->createCity('63.08', 'Kab. Hulu Sungai Utara');
        ($country->provinces->firstWhere('code', '63'))->createCity('63.02', 'Kab. Kotabaru');
        ($country->provinces->firstWhere('code', '63'))->createCity('63.09', 'Kab. Tabalong');
        ($country->provinces->firstWhere('code', '63'))->createCity('63.10', 'Kab. Tanah Bumbu');
        ($country->provinces->firstWhere('code', '63'))->createCity('63.01', 'Kab. Tanah Laut');
        ($country->provinces->firstWhere('code', '63'))->createCity('63.05', 'Kab. Tapin');
        ($country->provinces->firstWhere('code', '63'))->createCity('63.72', 'Kota Banjarbaru');
        ($country->provinces->firstWhere('code', '63'))->createCity('63.71', 'Kota Banjarmasin');
        ($country->provinces->firstWhere('code', '64'))->createCity('64.03', 'Kab. Berau');
        ($country->provinces->firstWhere('code', '64'))->createCity('64.07', 'Kab. Kutai Barat');
        ($country->provinces->firstWhere('code', '64'))->createCity('64.02', 'Kab. Kutai Kartanegara');
        ($country->provinces->firstWhere('code', '64'))->createCity('64.08', 'Kab. Kutai Timur');
        ($country->provinces->firstWhere('code', '64'))->createCity('64.11', 'Kab. Mahakam Ulu');
        ($country->provinces->firstWhere('code', '64'))->createCity('64.01', 'Kab. Paser');
        ($country->provinces->firstWhere('code', '64'))->createCity('64.09', 'Kab. Penajam Paser Utara');
        ($country->provinces->firstWhere('code', '64'))->createCity('64.71', 'Kota Balikpapan');
        ($country->provinces->firstWhere('code', '64'))->createCity('64.74', 'Kota Bontang');
        ($country->provinces->firstWhere('code', '64'))->createCity('64.72', 'Kota Samarinda');
        ($country->provinces->firstWhere('code', '62'))->createCity('62.04', 'Kab. Barito Selatan');
        ($country->provinces->firstWhere('code', '62'))->createCity('62.13', 'Kab. Barito Timur');
        ($country->provinces->firstWhere('code', '62'))->createCity('62.05', 'Kab. Barito Utara');
        ($country->provinces->firstWhere('code', '62'))->createCity('62.10', 'Kab. Gunung Mas');
        ($country->provinces->firstWhere('code', '62'))->createCity('62.03', 'Kab. Kapuas');
        ($country->provinces->firstWhere('code', '62'))->createCity('62.06', 'Kab. Katingan');
        ($country->provinces->firstWhere('code', '62'))->createCity('62.01', 'Kab. Kotawaringin Barat');
        ($country->provinces->firstWhere('code', '62'))->createCity('62.02', 'Kab. Kotawaringin Timur');
        ($country->provinces->firstWhere('code', '62'))->createCity('62.09', 'Kab. Lamandau');
        ($country->provinces->firstWhere('code', '62'))->createCity('62.12', 'Kab. Murung Raya');
        ($country->provinces->firstWhere('code', '62'))->createCity('62.11', 'Kab. Pulang Pisau');
        ($country->provinces->firstWhere('code', '62'))->createCity('62.07', 'Kab. Seruyan');
        ($country->provinces->firstWhere('code', '62'))->createCity('62.08', 'Kab. Sukamara');
        ($country->provinces->firstWhere('code', '62'))->createCity('62.71', 'Kota Palangka Raya');
        ($country->provinces->firstWhere('code', '65'))->createCity('65.01', 'Kab. Bulungan');
        ($country->provinces->firstWhere('code', '65'))->createCity('65.02', 'Kab. Malinau');
        ($country->provinces->firstWhere('code', '65'))->createCity('65.03', 'Kab. Nunukan');
        ($country->provinces->firstWhere('code', '65'))->createCity('65.04', 'Kab. Tana Tidung');
        ($country->provinces->firstWhere('code', '65'))->createCity('65.71', 'Kota Tarakan');
        ($country->provinces->firstWhere('code', '51'))->createCity('51.03', 'Kab. Badung');
        ($country->provinces->firstWhere('code', '51'))->createCity('51.06', 'Kab. Bangli');
        ($country->provinces->firstWhere('code', '51'))->createCity('51.08', 'Kab. Buleleng');
        ($country->provinces->firstWhere('code', '51'))->createCity('51.04', 'Kab. Gianyar');
        ($country->provinces->firstWhere('code', '51'))->createCity('51.01', 'Kab. Jembrana');
        ($country->provinces->firstWhere('code', '51'))->createCity('51.07', 'Kab. Karangasem');
        ($country->provinces->firstWhere('code', '51'))->createCity('51.05', 'Kab. Klungkung');
        ($country->provinces->firstWhere('code', '51'))->createCity('51.02', 'Kab. Tabanan');
        ($country->provinces->firstWhere('code', '51'))->createCity('51.71', 'Kota Denpasar');
        ($country->provinces->firstWhere('code', '52'))->createCity('52.06', 'Kab. Bima');
        ($country->provinces->firstWhere('code', '52'))->createCity('52.05', 'Kab. Dompu');
        ($country->provinces->firstWhere('code', '52'))->createCity('52.01', 'Kab. Lombok Barat');
        ($country->provinces->firstWhere('code', '52'))->createCity('52.02', 'Kab. Lombok Tengah');
        ($country->provinces->firstWhere('code', '52'))->createCity('52.03', 'Kab. Lombok Timur');
        ($country->provinces->firstWhere('code', '52'))->createCity('52.08', 'Kab. Lombok Utara');
        ($country->provinces->firstWhere('code', '52'))->createCity('52.04', 'Kab. Sumbawa');
        ($country->provinces->firstWhere('code', '52'))->createCity('52.07', 'Kab. Sumbawa Barat');
        ($country->provinces->firstWhere('code', '52'))->createCity('52.72', 'Kota Bima');
        ($country->provinces->firstWhere('code', '52'))->createCity('52.71', 'Kota Mataram');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.05', 'Kab. Alor');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.04', 'Kab. Belu');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.08', 'Kab. Ende');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.06', 'Kab. Flores Timur');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.01', 'Kab. Kupang');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.13', 'Kab. Lembata');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.21', 'Kab. Malaka');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.10', 'Kab. Manggarai');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.15', 'Kab. Manggarai Barat');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.19', 'Kab. Manggarai Timur');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.16', 'Kab. Nagekeo');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.09', 'Kab. Ngada');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.14', 'Kab. Rote Ndao');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.20', 'Kab. Sabu Raijua');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.07', 'Kab. Sikka');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.12', 'Kab. Sumba Barat');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.18', 'Kab. Sumba Barat Daya');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.17', 'Kab. Sumba Tengah');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.11', 'Kab. Sumba Timur');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.02', 'Kab. Timor Tengah Selatan');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.03', 'Kab. Timor Tengah Utara');
        ($country->provinces->firstWhere('code', '53'))->createCity('53.71', 'Kota Kupang');
        ($country->provinces->firstWhere('code', '76'))->createCity('76.02', 'Kab. Mamuju');
        ($country->provinces->firstWhere('code', '76'))->createCity('76.01', 'Kab. Pasangkayu');
        ($country->provinces->firstWhere('code', '76'))->createCity('76.04', 'Kab. Polewali Mandar');
        ($country->provinces->firstWhere('code', '76'))->createCity('76.03', 'Kab. Mamasa');
        ($country->provinces->firstWhere('code', '76'))->createCity('76.05', 'Kab. Majene');
        ($country->provinces->firstWhere('code', '76'))->createCity('76.06', 'Kab. Mamuju Tengah');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.03', 'Kab. Bantaeng');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.11', 'Kab. Barru');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.08', 'Kab. Bone');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.02', 'Kab. Bulukumba');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.16', 'Kab. Enrekang');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.06', 'Kab. Gowa');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.04', 'Kab. Jeneponto');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.01', 'Kab. Kepulauan Selayar');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.17', 'Kab. Luwu');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.24', 'Kab. Luwu Timur');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.22', 'Kab. Luwu Utara');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.09', 'Kab. Maros');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.10', 'Kab. Pangkajene dan Kepulauan');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.15', 'Kab. Pinrang');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.14', 'Kab. Sidenreng Rappang');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.07', 'Kab. Sinjai');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.12', 'Kab. Soppeng');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.05', 'Kab. Takalar');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.18', 'Kab. Tana Toraja');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.26', 'Kab. Toraja Utara');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.13', 'Kab. Wajo');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.71', 'Kota Makassar');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.73', 'Kota Palopo');
        ($country->provinces->firstWhere('code', '73'))->createCity('73.72', 'Kota Parepare');
        ($country->provinces->firstWhere('code', '72'))->createCity('72.01', 'Kab. Banggai');
        ($country->provinces->firstWhere('code', '72'))->createCity('72.07', 'Kab. Banggai Kepulauan');
        ($country->provinces->firstWhere('code', '72'))->createCity('72.11', 'Kab. Banggai Laut');
        ($country->provinces->firstWhere('code', '72'))->createCity('72.05', 'Kab. Buol');
        ($country->provinces->firstWhere('code', '72'))->createCity('72.03', 'Kab. Donggala');
        ($country->provinces->firstWhere('code', '72'))->createCity('72.06', 'Kab. Morowali');
        ($country->provinces->firstWhere('code', '72'))->createCity('72.12', 'Kab. Morowali Utara');
        ($country->provinces->firstWhere('code', '72'))->createCity('72.08', 'Kab. Parigi Moutong');
        ($country->provinces->firstWhere('code', '72'))->createCity('72.02', 'Kab. Poso');
        ($country->provinces->firstWhere('code', '72'))->createCity('72.10', 'Kab. Sigi');
        ($country->provinces->firstWhere('code', '72'))->createCity('72.09', 'Kab. Tojo Una-Una');
        ($country->provinces->firstWhere('code', '72'))->createCity('72.04', 'Kab. Tolitoli');
        ($country->provinces->firstWhere('code', '72'))->createCity('72.71', 'Kota Palu');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.01', 'Kab. Kolaka');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.02', 'Kab. Konawe');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.03', 'Kab. Muna');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.04', 'Kab. Buton');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.05', 'Kab. Konawe Selatan');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.06', 'Kab. Bombana');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.07', 'Kab. Wakatobi');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.08', 'Kab. Kolaka Utara');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.09', 'Kab. Konawe Utara');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.10', 'Kab. Buton Utara');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.11', 'Kab. Kolaka Timur');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.12', 'Kab. Konawe Kepulauan');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.13', 'Kab. Muna Barat');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.14', 'Kab. Buton Tengah');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.15', 'Kab. Buton Selatan');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.71', 'Kota Kendari');
        ($country->provinces->firstWhere('code', '74'))->createCity('74.72', 'Kota Baubau');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.01', 'Kab. Bolaang Mongondow');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.02', 'Kab. Minahasa');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.03', 'Kab. Kepulauan Sangihe');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.04', 'Kab. Kepulauan Talaud');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.05', 'Kab. Minahasa Selatan');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.06', 'Kab. Minahasa Utara');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.07', 'Kab. Minahasa Tenggara');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.08', 'Kab. Bolaang Mongondow Utara');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.09', 'Kab. Kepulauan Siau Tagulandang Biaro');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.10', 'Kab. Bolaang Mongondow Timur');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.11', 'Kab. Bolaang Mongondow Selatan');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.71', 'Kota Manado');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.72', 'Kota Bitung');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.73', 'Kota Tomohon');
        ($country->provinces->firstWhere('code', '71'))->createCity('71.74', 'Kota Kotamobagu');
        ($country->provinces->firstWhere('code', '75'))->createCity('75.02', 'Kab. Boalemo');
        ($country->provinces->firstWhere('code', '75'))->createCity('75.03', 'Kab. Bone Bolango');
        ($country->provinces->firstWhere('code', '75'))->createCity('75.01', 'Kab. Gorontalo');
        ($country->provinces->firstWhere('code', '75'))->createCity('75.05', 'Kab. Gorontalo Utara');
        ($country->provinces->firstWhere('code', '75'))->createCity('75.04', 'Kab. Pohuwato');
        ($country->provinces->firstWhere('code', '75'))->createCity('75.71', 'Kota Gorontalo');
        ($country->provinces->firstWhere('code', '81'))->createCity('81.04', 'Kab. Buru');
        ($country->provinces->firstWhere('code', '81'))->createCity('81.09', 'Kab. Buru Selatan');
        ($country->provinces->firstWhere('code', '81'))->createCity('81.07', 'Kab. Kepulauan Aru');
        ($country->provinces->firstWhere('code', '81'))->createCity('81.08', 'Kab. Maluku Barat Daya');
        ($country->provinces->firstWhere('code', '81'))->createCity('81.01', 'Kab. Maluku Tengah');
        ($country->provinces->firstWhere('code', '81'))->createCity('81.02', 'Kab. Maluku Tenggara');
        ($country->provinces->firstWhere('code', '81'))->createCity('81.03', 'Kab. Kepulauan Tanimbar');
        ($country->provinces->firstWhere('code', '81'))->createCity('81.06', 'Kab. Seram Bagian Barat');
        ($country->provinces->firstWhere('code', '81'))->createCity('81.05', 'Kab. Seram Bagian Timur');
        ($country->provinces->firstWhere('code', '81'))->createCity('81.71', 'Kota Ambon');
        ($country->provinces->firstWhere('code', '81'))->createCity('81.72', 'Kota Tual');
        ($country->provinces->firstWhere('code', '82'))->createCity('82.01', 'Kab. Halmahera Barat');
        ($country->provinces->firstWhere('code', '82'))->createCity('82.04', 'Kab. Halmahera Selatan');
        ($country->provinces->firstWhere('code', '82'))->createCity('82.02', 'Kab. Halmahera Tengah');
        ($country->provinces->firstWhere('code', '82'))->createCity('82.06', 'Kab. Halmahera Timur');
        ($country->provinces->firstWhere('code', '82'))->createCity('82.03', 'Kab. Halmahera Utara');
        ($country->provinces->firstWhere('code', '82'))->createCity('82.07', 'Kab. Pulau Morotai');
        ($country->provinces->firstWhere('code', '82'))->createCity('82.05', 'Kab. Kepulauan Sula');
        ($country->provinces->firstWhere('code', '82'))->createCity('82.08', 'Kab. Pulau Taliabu');
        ($country->provinces->firstWhere('code', '82'))->createCity('82.71', 'Kota Ternate');
        ($country->provinces->firstWhere('code', '82'))->createCity('82.72', 'Kota Tidore Kepulauan');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.18', 'Kab. Asmat');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.06', 'Kab. Biak Numfor');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.16', 'Kab. Boven Digoel');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.28', 'Kab. Deiyai');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.26', 'Kab. Dogiyai');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.27', 'Kab. Intan Jaya');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.03', 'Kab. Jayapura');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.02', 'Kab. Jayawijaya');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.11', 'Kab. Keerom');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.05', 'Kab. Kepulauan Yapen');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.23', 'Kab. Lanny Jaya');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.17', 'Kab. Mappi');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.20', 'Kab. Memberamo Raya');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.21', 'Kab. Membramo Tengah');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.01', 'Kab. Merauke');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.09', 'Kab. Mimika');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.04', 'Kab. Nabire');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.24', 'Kab. Nduga');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.08', 'Kab. Paniai');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.12', 'Kab. Pegunungan Bintang');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.25', 'Kab. Puncak');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.07', 'Kab. Puncak Jaya');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.10', 'Kab. Sarmi');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.19', 'Kab. Supiori');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.14', 'Kab. Tolikara');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.15', 'Kab. Waropen');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.13', 'Kab. Yahukimo');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.22', 'Kab. Yalimo');
        ($country->provinces->firstWhere('code', '91'))->createCity('91.71', 'Kota Jayapura');
        ($country->provinces->firstWhere('code', '92'))->createCity('92.03', 'Kab. Fakfak');
        ($country->provinces->firstWhere('code', '92'))->createCity('92.08', 'Kab. Kaimana');
        ($country->provinces->firstWhere('code', '92'))->createCity('92.02', 'Kab. Manokwari');
        ($country->provinces->firstWhere('code', '92'))->createCity('92.11', 'Kab. Manokwari Selatan');
        ($country->provinces->firstWhere('code', '92'))->createCity('92.10', 'Kab. Maybrat');
        ($country->provinces->firstWhere('code', '92'))->createCity('92.12', 'Kab. Pegunungan Arfak');
        ($country->provinces->firstWhere('code', '92'))->createCity('92.05', 'Kab. Raja Ampat');
        ($country->provinces->firstWhere('code', '92'))->createCity('92.01', 'Kab. Sorong');
        ($country->provinces->firstWhere('code', '92'))->createCity('92.04', 'Kab. Sorong Selatan');
        ($country->provinces->firstWhere('code', '92'))->createCity('92.09', 'Kab. Tambrauw');
        ($country->provinces->firstWhere('code', '92'))->createCity('92.06', 'Kab. Teluk Bintuni');
        ($country->provinces->firstWhere('code', '92'))->createCity('92.07', 'Kab. Teluk Wondama');
        ($country->provinces->firstWhere('code', '92'))->createCity('92.71', 'Kota Sorong');

        return true;
    }
}
