<?php

namespace Kevinpurwito\LaravelCountry\Tests;

use Kevinpurwito\LaravelCountry\CountryServiceProvider;

class TestCase extends \Orchestra\Testbench\TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function getPackageProviders($app)
    {
        return [
            CountryServiceProvider::class,
        ];
    }

    public function getEnvironmentSetUp($app)
    {
        include_once __DIR__ . '/../database/migrations/create_countries_table.php';
        include_once __DIR__ . '/../database/migrations/create_provinces_table.php';
        include_once __DIR__ . '/../database/migrations/create_cities_table.php';

        (new \CreateCountriesTable())->up();
        (new \CreateProvincesTable())->up();
        (new \CreateCitiesTable())->up();
    }
}
